### ISSUE TITLE
To much Schema.org markup!!?

### ISSUE THREAD

**Issue by jarofgreen** [OpenACalendar/OpenACalendar-Web-WordPress#57]
![screen shot 2016-12-01 at 16 16 07](https://cloud.githubusercontent.com/assets/85656/20801687/9a7e4f7a-b7e1-11e6-8161-073e6ac63275.png)

Just seen this. That markup is in a widget, in a side bar. Google shouldn't really take it.

Should we have markup if used from short code, on assumption it's a in main body of article/page and is important and not if widget?

Does having schema.org markup need to be an option?

**Comment by eggfriedrice** [comment]
Makes sense, but what if the widget was in a more prominent position on the index page? Then you'd probably want to get it indexed.

**Comment by jarofgreen** [comment]
It needs to be an option, doesn't it? Fair enough.
